apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: oc-demo
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/imeshsen/OCPSamples.git'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-compile
      params:
        - name: GOALS
          value:
            - clean
            - compile
        - name: MAVEN_IMAGE
          value: 'maven:3-eclipse-temurin-17-alpine'
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: shared-workspace
    - name: code-analysis
      params:
        - name: SONAR_HOST_URL
          value: >-
            https://sonar-imeshsenanayake1996-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
        - name: SONAR_TOKEN
          value: sqp_9e2831e34e6d8ca3a184768dea54c872c849ab71
        - name: SONAR_PROJECT_KEY
          value: sonar
      runAfter:
        - maven-compile
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: sonar-settings
          workspace: sonar-settings
    - name: cleanup-old-deployments
      params:
        - name: SCRIPT
          value: oc delete all -l app=spring-build
      runAfter:
        - code-analysis
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: shared-workspace
    - name: openshift-deployment
      params:
        - name: SCRIPT
          value: >-
            oc new-app openshift/java~https://github.com/imeshsen/OCPSamples.git
            --name=spring-build
      runAfter:
        - cleanup-old-deployments
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: shared-workspace
    - name: expose-svc
      params:
        - name: SCRIPT
          value: oc expose svc spring-build
      runAfter:
        - openshift-deployment
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: sonar-settings
    
