apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-tekton-pvc
  namespace: openshift-mta
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200mi
