kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-tekton-pvc
  namespace: oc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
