kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-tekton-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-6f571484-810b-4a79-9a30-a8f94c4a8a60
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi

