kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-tekton-pvc
  namespace: oc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: pvc-88622050-284a-47be-aa6d-02588d0af3bd
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
