kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
  namespace: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: spring-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: spring-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: spring-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/argo-demo/spring-app@sha256:fdeb3812937e2f93061c2b0462912a50f28821a45e3cf0767186bd4ab35f8ac6
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-03-07T11:34:47Z'
      lastTransitionTime: '2024-03-07T11:34:47Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-03-07T11:34:47Z'
      lastTransitionTime: '2024-03-07T11:34:01Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "spring-app-79b9dbb5f5" has successfully progressed.
