kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
  namespace: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: spring-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: spring-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: spring-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/argo-demo/spring-app@sha256:fdeb3812937e2f93061c2b0462912a50f28821a45e3cf0767186bd4ab35f8ac6
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          
