apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  limits:
    global:
      retention:
        days: 30
    tenants: 
      application:
        retention:
          days: 7
          streams:
            - days: 1
              selector: '{kubernetes_namespace_name=~".+"}' 
      infrastructure:
        retention:
          days: 7
          streams:
            - days: 1
              selector: '{kubernetes_namespace_name=~"openshift-cluster.+"}'
  managementState: Managed
  rules:
    enabled: true
  replicationFactor: 1
  size: 1x.extra-small
  storage:
    schemas:
    - effectiveDate: "2020-10-11"
      version: v11
    secret:
      name: logging-loki-s3
      type: s3
    tls:
      caName: openshift-service-ca.crt
  storageClassName: thin-csi
  tenants:
    mode: openshift-logging